# CORS Configuration
cors:
  allowed-origin-patterns: "http://localhost:*"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type
  exposed-headers: Authorization
  max-age: 3600
  allow-credentials: true

# Server Configuration
server:
  port: 9001
  servlet:
    context-path: /pos

# Logging Configuration
logging:
  level:
    com.increff.pos: DEBUG
